import "@/styles/reset.css";
import "@/styles/globals.css";

import { Providers } from "@/app/providers";
import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Mulish } from "next/font/google";

const MulishFont = Mulish({ subsets: ["latin", "cyrillic"] });

export const metadata = {
  title: "MM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={MulishFont.className}>
        <Providers>
          <Sidebar />

          <Header />

          <main className="content">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
